name:         ReplaceUmlaut
version:      0.1.5.3
license:      GPL
license-file: GPL_3
github:       andrewufrank/u4blog.git/uniform-cmdLineArgs
maintainer:   Andrew U. Frank <andrewufrank@gmail.com>
author:       Andrew Frank
copyright:    2021 Andrew U. Frank
category:     Text
synopsis:     converting text to properly encoded german umlauts
description: | 
  converts the convenient ae, oe and ue replacements for german 
  umlauts into their proper UTF-8 encoded umlauts - 
  respecting cases where the ae, oe and ue must remain
  based on a extensible list.
  Treats a file completely. 

spec-version: 0.30.0 # the hpack version minimally required 
extra-source-files:
  - ChangeLog.md
  - README.md
  - nichtUmlaute.txt
 

dependencies:
- base >= 4.7 && < 5
- uniformBase >=0.1.5
- uniform-fileio
# - completeMeta   # for the filehandling, split & move!
- uniform-json >= 0.1.5
- uniform-pandoc # only for extension md
# - uniform-convenience
- uniform-cmdLineArgs
# - pandoc
# - pandoc-types
- optparse-applicative
- dir-traverse
- text  # commonPrefixes
- transformers
# - aeson

library:
  source-dirs: 
  - src



# when:
# - condition: false
#   other-modules: Lib.ProcPandocDatei.hs

executables:
  replaceUmlaut:    # works on text files 
    main:                Main.hs
    source-dirs:          app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
      - ReplaceUmlaut
  # mdReplaceUmlaut:  #works for md files, reads language tag with MdDocHandling
  #   main:                 Main.hs
  #   source-dirs:          app4md
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #     - ReplaceUmlaut
  #   # - uniformBase 
  #   # - uniform-pandoc

  #   # - uniform-convenience
  #   # - uniform-cmdLineArgs
  #   # - uniform-error

tests:
  test1:
    main:                Testing.hs
    source-dirs:         tests
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - uniformBase 
    - HTF
    - ReplaceUmlaut 
