name:         ReplaceUmlaut
version:      0.0.1.1
license:      GPL
license-file: GPL_3
maintainer:   Andrew U. Frank <andrewufrank@gmail.com>
author:       Andrew Frank
copyright:    2021 Andrew U. Frank
category:     Text
synopsis:     converting text to properly encoded german umlauts
description: | 
  converts the convenient ae, oe and ue replacements for german 
  umlauts into their proper UTF-8 encoded umlauts - 
  respecting cases where the ae, oe and ue must remain
  based on a extensible list.
  version to restore with ghc 9.0.2


extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base >= 4.7 && < 5
- uniformBase ==0.1.4.2
- completeMeta   # for the filehandling, split & move!
- uniform-json
- uniform-pandoc
# - uniform-convenience
- uniform-cmdLineArgs
- pandoc
- pandoc-types
- optparse-applicative
- dir-traverse
- text  # for Data.Text - move to strings
# - aeson

library:
  source-dirs: 
  - src
  
# when:
# - condition: false
#   other-modules: Lib.ProcPandocDatei.hs

executables:
  replaceUmlaut:    # works on text files 
    main:                Main.hs
    source-dirs:          app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
      - ReplaceUmlaut
  # mdReplaceUmlaut:  #works for md files and read language tag
  #   main:                 Main.hs
  #   source-dirs:          app4md
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #     - ReplaceUmlaut
  #   # - uniformBase 
  #   # - uniform-pandoc

  #   # - uniform-convenience
  #   # - uniform-cmdLineArgs
  #   # - uniform-error

tests:
  test1:
    main:                Testing.hs
    source-dirs:         tests
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - uniformBase 
    - HTF
    - ReplaceUmlaut 