flags: {}
extra-package-dbs: []
packages:
- '.'
- ../uBase/uniformBase
# - ../uBase/uniform-algebras
# - ../uBase/uniform-error
- ../uBase/uniform-fileio
- ../uBase/uniform-strings
# - ../uBase/uniform-time
# - ../fromOthersInstalled/bibtex  # has a fix compared to hackage, see cabal
# -     ../completeMeta
- ../u4blog/uniform-cmdLineArgs
- ../u4blog/uniform-pandoc
- ../u4blog/uniform-json

extra-deps:
- uniform-algebras-0.1.5.1
- uniform-error-0.1.5.1
- uniform-time-0.1.5.1
- test-invariant-0.4.5.0
- dir-traverse-0.2.3.0
# @sha256:adcc128f201ff95131b15ffe41365dc99c50dc3fa3a910f021521dc734013bfa,2137
- snap-core-1.0.5.1
# @sha256:e08cc33b5ad34e8ccfa1436bfd19ac037ce15564d5652a21aaf71a8fd5959da9,9469
- readable-0.3.1
# @sha256:ea550740bbee9ae46c6bbf1c5e5185818a1d37509b855c640b0a7f2dfba6dc37,1121


resolver: lts-20.11
