flags: {}
extra-package-dbs: []
packages:
- '.'
- ../uniform/uniform-strings
- ../uniform/uniform-algebras
- ../uniform/uniform-convenience
- ../uniform/uniform-error
- ../uniform/uniform-time
- ../uniform/uniform-fileio
- ../uniform/uniform-http
- ../uniform/uniform-json
- ../uniform/uniform-pandoc
- ../fromOthersInstalled/bibtex  # has a fix compared to hackage, see cabal

extra-deps:
- test-invariant-0.4.5.0


resolver: lts-13.19
